-- Write a query to display for each store its store ID, city, and country.
USE SAKILA;
SELECT S.STORE_ID, CT.CITY, CO.COUNTRY
FROM SAKILA.STORE AS S
LEFT JOIN SAKILA.ADDRESS AS AD
ON S.ADDRESS_ID = AD.ADDRESS_ID
LEFT JOIN SAKILA.CITY AS CT
ON AD.CITY_ID = CT.CITY_ID
LEFT JOIN SAKILA.COUNTRY AS CO
ON CT.COUNTRY_ID = CO.COUNTRY_ID;

-- Write a query to display how much business, in dollars, each store brought in.
SELECT RENTAL_ID, COUNT(DISTINCT STAFF_ID) FROM SAKILA.PAYMENT
GROUP BY RENTAL_ID
HAVING COUNT(DISTINCT STAFF_ID) > 1;

SELECT ST.STORE_ID, SUM(PAY.AMOUNT)
FROM SAKILA.PAYMENT AS PAY
RIGHT JOIN SAKILA.STAFF AS ST
ON PAY.STAFF_ID = ST.STAFF_ID
GROUP BY ST.STORE_ID;


-- What is the average running time of films by category?
SELECT CAT.CATEGORY_ID, AVG(F.LENGTH)
FROM SAKILA.FILM AS F
LEFT JOIN SAKILA.FILM_CATEGORY AS CAT
ON F.FILM_ID = CAT.FILM_ID
GROUP BY CAT.CATEGORY_ID;

-- Which film categories are longest?
SELECT CAT.CATEGORY_ID, AVG(F.LENGTH) AS AVG_LENGTH
FROM SAKILA.FILM AS F
LEFT JOIN SAKILA.FILM_CATEGORY AS CAT
ON F.FILM_ID = CAT.FILM_ID
GROUP BY CAT.CATEGORY_ID
ORDER BY AVG_LENGTH DESC
LIMIT 1;

-- Display the most frequently rented movies in descending order.
SELECT F.TITLE, COUNT(R.RENTAL_ID) AS RENTED_MOVIES
FROM SAKILA.FILM AS F
LEFT JOIN SAKILA.INVENTORY AS INV
ON F.FILM_ID = INV.FILM_ID
LEFT JOIN SAKILA.RENTAL AS R
ON INV.INVENTORY_ID = R.INVENTORY_ID
GROUP BY TITLE 
ORDER BY RENTED_MOVIES DESC;

-- List the top five genres in gross revenue in descending order.
SELECT CAT.NAME, SUM(PAY.AMOUNT) AS GROSS_REVENUE
FROM SAKILA.CATEGORY AS CAT
INNER JOIN SAKILA.FILM_CATEGORY FC
ON CAT.CATEGORY_ID = FC.CATEGORY_ID
INNER JOIN SAKILA.FILM F 
ON F.FILM_ID = FC.FILM_ID
INNER JOIN SAKILA.INVENTORY INV
ON INV.FILM_ID = F.FILM_ID
INNER JOIN SAKILA.RENTAL R 
ON R.INVENTORY_ID = INV.INVENTORY_ID
INNER JOIN SAKILA.PAYMENT PAY
ON PAY.RENTAL_ID = R.RENTAL_ID
GROUP BY NAME
ORDER BY GROSS_REVENUE DESC;

-- Is "Academy Dinosaur" available for rent from Store 1? 
SELECT F.TITLE, INV.STORE_ID
FROM SAKILA.FILM AS F
INNER JOIN SAKILA.INVENTORY INV
ON F.FILM_ID = INV.FILM_ID
WHERE INV.STORE_ID = 1
AND F.TITLE = 'Academy Dinosaur';